### ISSUE TITLE
Prefixes and namespaces

### ISSUE THREAD

**Issue by fbrckman** [oSoc19/unshacled#197]
- [x] Modal with a table of namespaces.
- [x] Visualize using set prefixes.
- [x] Edit the list of existing namespaces.
- [x] Add new namespaces.
- [x] Delete namespaces.
- [x] Input validation.

**Comment by SvenLieber** [comment]
related to #177 

As discussed, something like a config or settings would be nice.
Prefixes and namespaces could then be stored in the config, so the UI can show the prefixes instead of the full base IRI.

Of course that means there should also be a way in the UI to reach this prefix-part of the config, e.g. via a menu in the header (see the RMLEditor for an example).
